language: scala
sudo: false
jdk: openjdk8
scala:
  - 2.12.10
cache:
  directories:
    - $HOME/.ivy2
matrix:
  include:
    - scala:
        - 2.11.12
      env:
        - TEST_SPARK_VERSION="2.3.4"
    - env:
        - TEST_SPARK_VERSION="2.4.4"
    - jdk: openjdk11
      env:
        - TEST_SPARK_VERSION="3.0.0-preview"
script:
  - sbt -Dspark.testVersion=$TEST_SPARK_VERSION ++$TRAVIS_SCALA_VERSION clean scalastyle test:scalastyle mimaReportBinaryIssues coverage test coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
